#!/usr/bin/env node
var fs=require("fs")
var toy=require("./toy.js")
var vm=require("vm")
var util=require("util")
var readline = require('readline')
var argv = process.argv
console.log(argv)
console.log("Try to use code9")
// REPL
if (argv.length==2){
	
	console.log("Interactive mode");
	console.log("Press Ctrl + C to quit\n");

	var input_str=""

	var rl = readline.createInterface({
	  input: process.stdin,
	  output: process.stdout
	})

	rl.setPrompt('toy> ')
	rl.prompt()

	var to_run=""
	var env = toy.ENV_LIST
	rl.on('line', function(line) {
		var parsed_obj = toy.parseString(line)
		parsed_obj = parsed_obj[0]
		var return_value = toy.toy(parsed_obj , env , "" )
		console.log(return_value)
		rl.setPrompt('toy> ')
		rl.prompt()
	})

	rl.on('close', function() {
	  console.log('Quit walley')
	  process.exit(0)
	});
	
}
// test running time 
else if (argv.length==3 && argv[2]==='test'){
	console.log("Test mode");
	console.log("Press Ctrl + C to quit\n");

	var input_str=""

	var rl = readline.createInterface({
	  input: process.stdin,
	  output: process.stdout
	})

	rl.setPrompt('toy> ')
	rl.prompt()

	var to_run=""
	var env = toy.ENV_LIST
	rl.on('line', function(line) {
		var start = new Date().getTime()
		
		var parsed_obj = toy.parseString(line)
		parsed_obj = parsed_obj[0]
		var return_value = toy.toy(parsed_obj , env , "" )
		console.log(return_value)

		var end = new Date().getTime()
		console.log("Time collapse: "+(end-start) + " ms")

		rl.setPrompt('toy> ')
		rl.prompt()
	})

	rl.on('close', function() {
	  console.log('Quit walley')
	  process.exit(0)
	});
}
// run file
else if (argv.length==3){
	var file_name = argv[2]
	if (typeof(file_name)=="undefined"){
		console.log("No input file..")
		process.exit(0)
	}
	// get content of file
	var content_in_file=fs.readFileSync(file_name,"utf8")
	// parse
	var parsed_obj = toy.parseString(content_in_file)
	// run string
	toy.toy_language(parsed_obj, toy.ENV_LIST ,"" )
}

// show env
else if (argv.length==4 && argv[2]=="env"){
	var file_name = argv[3]
	if (typeof(file_name)=="undefined"){
		console.log("No input file..")
		process.exit(0)
	}
	// get content of file
	var content_in_file=fs.readFileSync(file_name,"utf8")
	// parse
	var parsed_obj = toy.parseString(content_in_file)
	// run string
	var env = toy.toy_language(parsed_obj, toy.ENV_LIST ,"" )
	toy.printArray(env)
}

// COMPRESS
else if (argv.length == 4 && argv[2] == "compress"){
	var file_name = argv[3]
	var content_in_file = fs.readFileSync(file_name,"utf8")
	console.log(content_in_file)
}



